Minor set of feature releases - not yet released on github.
Includes the following changes:

- Clarifying email job in auth api and changing email address to service inbox (#59)
- bug fix - f1545 migrator script missing history items which are full datasetdomaininfo's.
- RRAPIS-1545 (Minor): Fetch/list by access info URI - Back end only (#57)
- RRAPIS-1532 (Minor): Prov graph upstream and downstream filter (#56)
- RRAPIS-1398(Minor): ID service folder rename (#55)

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.9.5 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.0.2 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -42,6 +42,7 @@ migrate_usage() {
   printf "  %s   Migrations required for f1442 feature - adds the versioning info version = 1 for Entity category items\n" "f1442-migration                      "
   printf "  %s   Migrations required for f1458 feature - adds the versioning info version = 1 for Entity category items\n" "f1458-migration                      "
   printf "  %s   CAUTION: Clears all items from the registry and graph store for a given stage. This does not allow PROD by default. You will need to manually clear PROD. This is a migration used when other forms of migration are too time intensive for test items (usually when manual intervention required).\n" "clear-app-stage                      "
+  printf "  %s   Migrations required for f1545 feature - Access Info URI in non-reposited datasets for fetch\n" "f1545-migration                      "
   echo
 
   # :command.long_usage
@@ -80,11 +81,6 @@ migrate_history_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -94,6 +90,11 @@ migrate_history_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -129,11 +130,6 @@ migrate_f1339_modelrun_display_name_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -143,6 +139,11 @@ migrate_f1339_modelrun_display_name_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -178,11 +179,6 @@ migrate_f1249_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -192,6 +188,11 @@ migrate_f1249_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -227,11 +228,6 @@ migrate_f1249_f1247_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -241,6 +237,11 @@ migrate_f1249_f1247_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -276,11 +277,6 @@ migrate_f1176_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -290,6 +286,11 @@ migrate_f1176_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -316,11 +317,6 @@ migrate_f1442_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -330,6 +326,11 @@ migrate_f1442_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -365,11 +366,6 @@ migrate_f1458_migration_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--apply"
@@ -379,6 +375,11 @@ migrate_f1458_migration_usage() {
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -414,15 +415,15 @@ migrate_clear_app_stage_usage() {
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
     # :command.usage_flags
     # :flag.usage
     printf "  %s\n" "--reuse_venv"
     printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
     # :command.usage_args
@@ -432,6 +433,55 @@ migrate_clear_app_stage_usage() {
     printf "  %s\n" "STAGE"
     printf "    The application stage to target\n"
     printf "    Allowed: TEST, DEV, STAGE\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+migrate_f1545_migration_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "migrate f1545-migration - Migrations required for f1545 feature - Access Info URI in non-reposited datasets for fetch\n"
+    echo
+
+  else
+    printf "migrate f1545-migration - Migrations required for f1545 feature - Access Info URI in non-reposited datasets for fetch\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  migrate f1545-migration STAGE [OPTIONS]\n"
+  printf "  migrate f1545-migration --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--apply"
+    printf "    Apply the changes - do not run in dry run mode.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--reuse_venv"
+    printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "STAGE"
+    printf "    The application stage to target\n"
+    printf "    Allowed: TEST, DEV, STAGE, PROD\n"
     echo
 
   fi
@@ -463,8 +513,8 @@ normalize_input() {
 }
 # :command.inspect_args
 inspect_args() {
-  readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
   if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
     for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
   else
@@ -479,6 +529,14 @@ inspect_args() {
       echo "- \${other_args[$i]} = ${other_args[$i]}"
     done
   fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+  fi
+
 }
 
 # :command.command_functions
@@ -1166,6 +1224,91 @@ migrate_clear_app_stage_command() {
 
 }
 
+# :command.function
+migrate_f1545_migration_command() {
+  # src/f1545_migration_command.sh
+  function venv() {
+      # function to setup python venv
+      if [[ ! $reuse_venv ]]; then
+          echo "Setting up venv"
+
+          # clear any existing venv
+          rm -rf .venv
+
+          # create new and install requirements
+          python3.10 -m venv .venv
+          source .venv/bin/activate
+          pip install -r requirements.txt
+      else
+          echo "Reusing existing virtual environment"
+          source .venv/bin/activate
+      fi
+
+  }
+
+  # Constants
+  pre_migration_prefix="f1545_pre"
+  post_migration_prefix="f1545_post"
+
+  apply=${args[--apply]}
+  stage=${args[stage]}
+  reuse_venv=${args[--reuse_venv]}
+
+  # generate the apply part of argument if supplied
+  apply_arg=""
+  if [[ $apply ]]; then
+      echo "Changes will be applied since --apply flag was specified"
+      apply_arg="--apply"
+  fi
+
+  # save starting point
+  current_dir=$(pwd)
+
+  # Step one  - export registry
+
+  echo "Moving to export tooling"
+  cd admin-tooling/registry
+
+  # setup venv
+  venv
+
+  echo "Running export, you may need to sign in"
+
+  export_output_name="dumps/${pre_migration_prefix}_${stage}.json"
+  migration_output_name="dumps/${post_migration_prefix}_${stage}.json"
+
+  python import_export.py export-items ${stage} --output ${export_output_name}
+
+  echo "Export completed"
+
+  # Step two - migrate the items (uses migrations script in admin tooling)
+  cd ${current_dir}
+
+  echo "Moving to migration tooling"
+  cd admin-tooling/registry
+
+  echo "Venv already setup here"
+
+  echo "Running migration"
+  python import_export.py modifiers f1545-migration ${stage} ${export_output_name} ${migration_output_name}
+
+  echo "Migration completed locally - running import to registry"
+
+  # Step three - import the items
+  cd ${current_dir}
+
+  echo "Moving to import tooling"
+  cd admin-tooling/registry
+
+  echo "Venv already setup here"
+
+  echo "Running import"
+  python import_export.py import-items ${stage} ${migration_output_name} SYNC_ADD_OR_OVERWRITE ${apply_arg}
+
+  echo "Process completed"
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -1248,6 +1391,13 @@ parse_requirements() {
       action="clear-app-stage"
       shift
       migrate_clear_app_stage_parse_requirements "$@"
+      shift $#
+      ;;
+
+    f1545-migration)
+      action="f1545-migration"
+      shift
+      migrate_f1545_migration_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1877,6 +2027,83 @@ migrate_clear_app_stage_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+migrate_f1545_migration_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        migrate_f1545_migration_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="f1545-migration"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --apply)
+
+        # :flag.case_no_arg
+        args['--apply']=1
+        shift
+        ;;
+
+      # :flag.case
+      --reuse_venv)
+
+        # :flag.case_no_arg
+        args['--reuse_venv']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['stage']+x} ]]; then
+
+          args['stage']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['stage']+x} ]]; then
+    printf "missing required argument: STAGE\nusage: migrate f1545-migration STAGE [OPTIONS]\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+    printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
+    exit 1
+  fi
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -1890,84 +2117,22 @@ initialize() {
 # :command.run
 run() {
   declare -A args=()
+  declare -A deps=()
   declare -a other_args=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
   case "$action" in
-    "history-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_history_migration_usage
-      else
-        migrate_history_migration_command
-      fi
-      ;;
-
-    "f1339-modelrun-display-name-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1339_modelrun_display_name_migration_usage
-      else
-        migrate_f1339_modelrun_display_name_migration_command
-      fi
-      ;;
-
-    "f1249-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1249_migration_usage
-      else
-        migrate_f1249_migration_command
-      fi
-      ;;
-
-    "f1249-f1247-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1249_f1247_migration_usage
-      else
-        migrate_f1249_f1247_migration_command
-      fi
-      ;;
-
-    "f1176-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1176_migration_usage
-      else
-        migrate_f1176_migration_command
-      fi
-      ;;
-
-    "f1442-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1442_migration_usage
-      else
-        migrate_f1442_migration_command
-      fi
-      ;;
-
-    "f1458-migration")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_f1458_migration_usage
-      else
-        migrate_f1458_migration_command
-      fi
-      ;;
-
-    "clear-app-stage")
-      if [[ ${args['--help']:-} ]]; then
-        long_usage=yes
-        migrate_clear_app_stage_usage
-      else
-        migrate_clear_app_stage_command
-      fi
-      ;;
-
+    "history-migration") migrate_history_migration_command ;;
+    "f1339-modelrun-display-name-migration") migrate_f1339_modelrun_display_name_migration_command ;;
+    "f1249-migration") migrate_f1249_migration_command ;;
+    "f1249-f1247-migration") migrate_f1249_f1247_migration_command ;;
+    "f1176-migration") migrate_f1176_migration_command ;;
+    "f1442-migration") migrate_f1442_migration_command ;;
+    "f1458-migration") migrate_f1458_migration_command ;;
+    "clear-app-stage") migrate_clear_app_stage_command ;;
+    "f1545-migration") migrate_f1545_migration_command ;;
   esac
 }
 
