Release v2.4 including the following PR changes:     RRAPIS-1580 (Minor): Moving model version annotation from workflow template to model run (#68)
    Moves the "software_version" field from the model run workflow template to the model run itself, and renames it "model_version".

    This change will allow modellers to annotate model versions more naturally. For example, it is unlikely that every time a model was changed (say in a git repo), that a new workflow template would be desired. Instead, the modeller can annotate the git hash or other version identifier for each model run, reusing the same template. The model run workflow template retains it's own versioning capabilities, where required.

    The migration finds all model run workflow templates, and moves the version annotation to all model runs which reference it.

    I have updated the docs where appropriate to reference this new field.

    RRAPIS-1583 (Minor): Data store API S3 path code refactor (#69)

    improves authorisation s3 path code due to identified poor code quality.

    RRAPIS-1575 (Minor): Improved graph restore functionality utilising job system and expanding to all provenance types  (#66)

    Adds a restore graph functionality which utilises the job system efficiently to restore provenance only for existing registry items.

    Locking moto library

    Adding a linked/unlinked dataset + summary stats functionality.

    RRAPIS-1581 (Minor): allow storage of files for externally reposited datasets (#67)

diff --git a/migrate b/migrate
--- a/migrate
+++ b/migrate
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.0.2 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -43,6 +43,7 @@ migrate_usage() {
   printf "  %s   Migrations required for f1458 feature - adds the versioning info version = 1 for Entity category items\n" "f1458-migration                      "
   printf "  %s   CAUTION: Clears all items from the registry and graph store for a given stage. This does not allow PROD by default. You will need to manually clear PROD. This is a migration used when other forms of migration are too time intensive for test items (usually when manual intervention required).\n" "clear-app-stage                      "
   printf "  %s   Migrations required for f1545 feature - Access Info URI in non-reposited datasets for fetch\n" "f1545-migration                      "
+  printf "  %s   Migrations required for f1580 feature - moves the software_version field from MRWT into model run(s) which use it\n" "f1580-migration                      "
   echo
 
   # :command.long_usage
@@ -487,6 +488,55 @@ migrate_f1545_migration_usage() {
   fi
 }
 
+# :command.usage
+migrate_f1580_migration_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "migrate f1580-migration - Migrations required for f1580 feature - moves the software_version field from MRWT into model run(s) which use it\n"
+    echo
+
+  else
+    printf "migrate f1580-migration - Migrations required for f1580 feature - moves the software_version field from MRWT into model run(s) which use it\n"
+    echo
+
+  fi
+
+  printf "%s\n" "Usage:"
+  printf "  migrate f1580-migration STAGE [OPTIONS]\n"
+  printf "  migrate f1580-migration --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--apply"
+    printf "    Apply the changes - do not run in dry run mode.\n"
+    echo
+
+    # :flag.usage
+    printf "  %s\n" "--reuse_venv"
+    printf "    Don't rebuild the python virtual environments\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "STAGE"
+    printf "    The application stage to target\n"
+    printf "    Allowed: TEST, DEV, STAGE, PROD\n"
+    echo
+
+  fi
+}
+
 # :command.normalize_input
 normalize_input() {
   local arg flags
@@ -516,7 +566,9 @@ inspect_args() {
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
-    for k in "${sorted_keys[@]}"; do echo "- \${args[$k]} = ${args[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
   else
     echo args: none
   fi
@@ -534,9 +586,19 @@ inspect_args() {
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
     echo deps:
-    for k in "${sorted_keys[@]}"; do echo "- \${deps[$k]} = ${deps[$k]}"; done
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
   fi
 
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
 }
 
 # :command.command_functions
@@ -1309,6 +1371,91 @@ migrate_f1545_migration_command() {
 
 }
 
+# :command.function
+migrate_f1580_migration_command() {
+  # src/f1580_migration_command.sh
+  function venv() {
+      # function to setup python venv
+      if [[ ! $reuse_venv ]]; then
+          echo "Setting up venv"
+
+          # clear any existing venv
+          rm -rf .venv
+
+          # create new and install requirements
+          python3.10 -m venv .venv
+          source .venv/bin/activate
+          pip install -r requirements.txt
+      else
+          echo "Reusing existing virtual environment"
+          source .venv/bin/activate
+      fi
+
+  }
+
+  # Constants
+  pre_migration_prefix="f1580_pre"
+  post_migration_prefix="f1580_post"
+
+  apply=${args[--apply]}
+  stage=${args[stage]}
+  reuse_venv=${args[--reuse_venv]}
+
+  # generate the apply part of argument if supplied
+  apply_arg=""
+  if [[ $apply ]]; then
+      echo "Changes will be applied since --apply flag was specified"
+      apply_arg="--apply"
+  fi
+
+  # save starting point
+  current_dir=$(pwd)
+
+  # Step one  - export registry
+
+  echo "Moving to export tooling"
+  cd admin-tooling/registry
+
+  # setup venv
+  venv
+
+  echo "Running export, you may need to sign in"
+
+  export_output_name="dumps/${pre_migration_prefix}_${stage}.json"
+  migration_output_name="dumps/${post_migration_prefix}_${stage}.json"
+
+  python import_export.py export-items ${stage} --output ${export_output_name}
+
+  echo "Export completed"
+
+  # Step two - migrate the items (uses migrations script in admin tooling)
+  cd ${current_dir}
+
+  echo "Moving to migration tooling"
+  cd admin-tooling/registry
+
+  echo "Venv already setup here"
+
+  echo "Running migration"
+  python import_export.py modifiers f1580-migration ${stage} ${export_output_name} ${migration_output_name}
+
+  echo "Migration completed locally - running import to registry"
+
+  # Step three - import the items
+  cd ${current_dir}
+
+  echo "Moving to import tooling"
+  cd admin-tooling/registry
+
+  echo "Venv already setup here"
+
+  echo "Running import"
+  python import_export.py import-items ${stage} ${migration_output_name} SYNC_ADD_OR_OVERWRITE ${apply_arg}
+
+  echo "Process completed"
+
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flags_filter
@@ -1398,6 +1545,13 @@ parse_requirements() {
       action="f1545-migration"
       shift
       migrate_f1545_migration_parse_requirements "$@"
+      shift $#
+      ;;
+
+    f1580-migration)
+      action="f1580-migration"
+      shift
+      migrate_f1580_migration_parse_requirements "$@"
       shift $#
       ;;
 
@@ -1507,7 +1661,7 @@ migrate_history_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -1584,7 +1738,7 @@ migrate_f1339_modelrun_display_name_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -1661,7 +1815,7 @@ migrate_f1249_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -1738,7 +1892,7 @@ migrate_f1249_f1247_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -1874,7 +2028,7 @@ migrate_f1442_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -1951,7 +2105,7 @@ migrate_f1458_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -2020,7 +2174,7 @@ migrate_clear_app_stage_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE" >&2
     exit 1
   fi
@@ -2097,7 +2251,84 @@ migrate_f1545_migration_parse_requirements() {
   fi
 
   # :command.whitelist_filter
-  if [[ ! ${args['stage']} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
+    printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+migrate_f1580_migration_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        migrate_f1580_migration_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="f1580-migration"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --apply)
+
+        # :flag.case_no_arg
+        args['--apply']=1
+        shift
+        ;;
+
+      # :flag.case
+      --reuse_venv)
+
+        # :flag.case_no_arg
+        args['--reuse_venv']=1
+        shift
+        ;;
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['stage']+x} ]]; then
+
+          args['stage']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['stage']+x} ]]; then
+    printf "missing required argument: STAGE\nusage: migrate f1580-migration STAGE [OPTIONS]\n" >&2
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['stage']:-} ]] && [[ ! ${args['stage']:-} =~ ^(TEST|DEV|STAGE|PROD)$ ]]; then
     printf "%s\n" "stage must be one of: TEST, DEV, STAGE, PROD" >&2
     exit 1
   fi
@@ -2119,6 +2350,7 @@ run() {
   declare -A args=()
   declare -A deps=()
   declare -a other_args=()
+  declare -a env_var_names=()
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
@@ -2133,6 +2365,7 @@ run() {
     "f1458-migration") migrate_f1458_migration_command ;;
     "clear-app-stage") migrate_clear_app_stage_command ;;
     "f1545-migration") migrate_f1545_migration_command ;;
+    "f1580-migration") migrate_f1580_migration_command ;;
   esac
 }
 
